extends Node

const green := "Misa"
const blue := "Ari"
const red := "Clara"
const green_teacher := "Professor Hilbert"
const yellow_teacher := "Olivia"
const yellow_teacher_formally := "Dr. Franklin"
const red_teacher := "Ms. Phenia"
const cyan_ai := "Luna"
const sacred := "Life"
const plain := "Jane"
const average := "Joe"

const deepest_layer := "Cirruseng"
const imaginary := "Imaginary Space"
const real := "Real Space"

const bookcase_anim := "default"
const bookcase_taken_anim := "taken"
const read_anim := "read"
const reading_anim := "reading"
const focus_anim := "focus"
const sprout_anim := "grow"
const sprouting_anim := "bloom"

const yellow_aspect := "Lightning"
const green_aspect := "Earth"
const red_aspect := "Fire"
const blue_aspect := "Immaterial"

const revealer = "Revealing Eyepiece"

var YELLOW = "Richy"
var RED = "Clara"
var BLUE_FATHER = "Lord Arwin"
var YELLOW_TEACHER = "Miss Olivia"
var GREEN_TEACHER = "Mr. Hilbert"
var RED_TEACHER = "Miss Phenia"
var BLUE_TEACHER = "Martin"
var CAT = "Robo-Cat"
var CARETAKER = "The Caretaker"
var PRINCIPAL = "The Principal"
var WISHMAKER = "Wishmaker"
var IMAGINER = "Worldmaster"
var SEAL = "Safety Construct"
var OUROBOROS = "Obo"

var YELLOW_ASPECT = "Lightning"
var GREEN_ASPECT = "Earth"
var RED_ASPECT = "Fire"
var BLUE_ASPECT = "Air"
var ASPECTLESS = "Magicless"
var REAL_SPACE = "Real Space"
var DUAL_SPACE = "Dual Space"
var CIRRUSENG = "Cirruseng"

var GREAT_HALL = "Great Hall"

var TRAVELLER = "Remembering"
var IGNITER = "Burning"

var FUTURE = "Real Transcripts of Real Fortune Telling (TM)"
var SHADOW = "Shadow"
var CERTAINTY = "Certainty"

