extends Node

const green := "Misa"
const blue := "Ari"
const red := "Clara"
const yellow := "Richy"
const amber := "Miranda"
const lime := "Bill"
const maroon := "Kamo"
const green_teacher := "Professor Hilbert"
const yellow_teacher := "Olivia"
const yellow_teacher_formally := "Dr. Franklin"
const red_teacher := "Dr. Phenia"
const blue_teacher := "Dr. Marvin"
const cat := "Robo-cat"
const cyan_ai := "Moon"
const sacred := "Life"
const plain := "Jane"
const average := "Joe"

const deepest_layer := "Cirruseng"
const imaginary := "Imaginary Space"
const real := "Real Space"

const bookcase_anim := "default"
const bookcase_taken_anim := "taken"
const read_anim := "read"
const reading_anim := "reading"
const focus_anim := "focus"
const sprout_anim := "grow"
const sprouting_anim := "bloom"

const yellow_aspect := "Lightning"
const green_aspect := "Earth"
const red_aspect := "Fire"
const blue_aspect := "Immaterial"

const revealer = "Revealing Eyepiece"

var OUROBOROS = "Obo"
